### ISSUE TITLE
Getting an argument crash on android 5.1 devices

### ISSUE THREAD

**Issue by ANIBIT14** [hieuvp/react-native-fingerprint-scanner#153]
Getting the following crash on android 5.1 devices in production app hoping someone can help asap:-
Fatal Exception: com.facebook.react.bridge.NativeArgumentsParseException: ReactNativeFingerprintScanner.authenticate got 2 arguments, expected 6
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java)
       at android.os.Looper.loop(Looper.java:210)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java)
       at java.lang.Thread.run(Thread.java:818)

**Comment by mikehardy** [comment]
argument count mismatches between javascript and native is almost always updates that went wrong, or stale things somewhere. I recommend `npx react-native-clean-project` and a fresh attempt

**Comment by ANIBIT14** [comment]
@mikehardy it is just happening for android 5.1 devices, it is not breaking on any other os version,

**Comment by mikehardy** [comment]
I just re-read the report. My statement still stands.

**Comment by ANIBIT14** [comment]
@mikehardy thanks, will recheck with the above solution
