### ISSUE TITLE
Android - Fingerprint not working after I upload to google play store

### ISSUE THREAD

**Issue by opolyo01** [hieuvp/react-native-fingerprint-scanner#75]
I see fingerprint when I run my debug build, but after uploading to google play store it stops working.  Here's the exception I am getting when doing adb logcat.  I noticed examples and manual setup have a difference in having or not

<uses-permission android:name="android.permission.USE_FINGERPRINT" />

Do I need this line in AndroidManifest.xml?

Here's the exception I get in prod:
```
02-06 18:31:34.303 13448 13476 E MzFingerManager: get fp method time, mService = null
02-06 18:31:34.305 13448 13476 W System.err: java.lang.RuntimeException
02-06 18:31:34.306 13448 13476 W System.err: 	at com.fingerprints.service.FingerprintManager.<init>(FingerprintManager.java:634)
02-06 18:31:34.306 13448 13476 W System.err: 	at com.fingerprints.service.FingerprintManager.open(FingerprintManager.java:550)
02-06 18:31:34.306 13448 13476 W System.err: 	at com.wei.android.lib.fingerprintidentify.impl.MeiZuFingerprint.<init>(MeiZuFingerprint.java:41)
02-06 18:31:34.306 13448 13476 W System.err: 	at com.wei.android.lib.fingerprintidentify.FingerprintIdentify.<init>(FingerprintIdentify.java:62)
02-06 18:31:34.306 13448 13476 W System.err: 	at com.hieuvp.fingerprint.ReactNativeFingerprintScannerModule.getFingerprintIdentify(ReactNativeFingerprintScannerModule.java:48)
02-06 18:31:34.306 13448 13476 W System.err: 	at com.hieuvp.fingerprint.ReactNativeFingerprintScannerModule.getErrorMessage(ReactNativeFingerprintScannerModule.java:60)
02-06 18:31:34.306 13448 13476 W System.err: 	at com.hieuvp.fingerprint.ReactNativeFingerprintScannerModule.isSensorAvailable(ReactNativeFingerprintScannerModule.java:120)
02-06 18:31:34.306 13448 13476 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
02-06 18:31:34.306 13448 13476 W System.err: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
02-06 18:31:34.306 13448 13476 W System.err: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
02-06 18:31:34.306 13448 13476 W System.err: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
02-06 18:31:34.306 13448 13476 W System.err: 	at android.os.Handler.handleCallback(Handler.java:790)
02-06 18:31:34.306 13448 13476 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-06 18:31:34.306 13448 13476 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
02-06 18:31:34.306 13448 13476 W System.err: 	at android.os.Looper.loop(Looper.java:164)
02-06 18:31:34.306 13448 13476 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
02-06 18:31:34.306 13448 13476 W System.err: 	at java.lang.Thread.run(Thread.java:764)
02-06 18:31:34.419 13448 13448 I zygote  : Deoptimizing void com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(int, int, int, int, int, int) due to JIT inline cache
```

**Comment by phillbaker** [comment]
@opolyo01 are you still experiencing this issue?

>  noticed examples and manual setup have a difference in having or not
> Do I need this line in AndroidManifest.xml?

What line are you referring to?

Similar issues that might apply here:
* https://github.com/hieuvp/react-native-fingerprint-scanner/issues/72
* https://github.com/hieuvp/react-native-fingerprint-scanner/issues/20

Have you confirmed that the appropriate permissions listed in the readme are included in your build?

**Comment by shuffledex** [comment]
same problem here

**Comment by phillbaker** [comment]
@shuffledex can you provide any feedback on the posted workarounds?

**Comment by phillbaker** [comment]
I believe this was the same underlying issue as https://github.com/hieuvp/react-native-fingerprint-scanner/pull/92.

**Comment by OneStromberg** [comment]
Have the same problem here, reproduces when there aren't any fingerprints on the phone. 
@phillbaker I increased **compileSdkVersion** and **buildToolsVersion** of the lib in _build.gradle_, but still can see the issue.
It's closed, so I hope that I'm doing something wrong...
